spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/memorygame}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:memorygame}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:memorygame}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
server.port=8080
